import gql from 'graphql-tag'
  
export const ALL_QUOTES_QUERY = gql`
      query GET_ALL_QUOTES ($limit:Int,$offset:Int,$employeeEmail:String){
      quotes (limit:$limit,offset:$offset,employeeEmail:$employeeEmail){
          count
          total
          results{
          id
          version
          employeeEmail
          quoteState
          quoteNumber
          percentageDiscount
          totalPrice{
              centAmount,
              currencyCode
          }
          company{
              id,
              name
          }
          lineItems{
            quantity
            price{
              value{
                currencyCode
                centAmount
              }
            }
            originalPrice{
              centAmount
              currencyCode
            }
            totalPrice{
              centAmount
              currencyCode
            }
            nameAllLocales{
              locale
              value
            }
            variant{
              sku
              price{
                value{
                  centAmount
                  currencyCode
                }
              }
            }
          }
          }
      }
      }
      `;
export const GET_SUBMITTED_QUOTES = gql`
query GET_SUBMITTED_QUOTES ($limit:Int,$offset:Int,$quoteState:[String!]){
quotes (limit:$limit,offset:$offset,quoteState:$quoteState){
    count
    total
    results{
    id
    version
    employeeEmail
    quoteState
    quoteNumber
    percentageDiscount
    totalPrice{
        centAmount,
        currencyCode
    }
    company{
        id,
        name
    }
    lineItems{
    quantity
    price{
        value{
        currencyCode
        centAmount
        }
    }
    originalPrice{
        centAmount
        currencyCode
    }
    totalPrice{
        centAmount
        currencyCode
    }
    nameAllLocales{
        locale
        value
    }
    variant{
        sku
        price{
        value{
            centAmount
            currencyCode
        }
        }
    }
    }
    }
}
}
`;

export const UPDATE_QUOTE_MUTATION = gql`
mutation UPDATE_QUOTE_MUTATION($id:String!,$version:Long!,$actions:[QuoteUpdateAction!]!){
  updateQuote(id:$id,version:$version,actions:$actions){
    id
    version
    employeeEmail
    quoteState
    quoteNumber
    percentageDiscount
    totalPrice{
        centAmount,
        currencyCode
    }
    company{
        id,
        name
    }
    lineItems{
      quantity
      price{
        value{
          currencyCode
          centAmount
        }
      }
      originalPrice{
        centAmount
        currencyCode
      }
      totalPrice{
        centAmount
        currencyCode
      }
      nameAllLocales{
        locale
        value
      }
      variant{
        sku
        price{
          value{
            centAmount
            currencyCode
          }
        }
      }
    }
  }
}
`;


export const CREATE_QUOTE_MUTATION = gql`
mutation CREATE_QUOTE_MUTATION($draft:CreateQuoteDraft!){
  createQuote(draft:$draft){
    id
    employeeId
    employeeEmail
  }
}
`;

export const GET_EMPLOYEE_DETAIL_QUERY=gql`
query($where:String){
    employees(where:$where){
      offset
      results{
        employeeNumber
        email
        id
        companyName
        customerGroup{
          key
        }
      }
    }
  }
`


export const GET_QUOTE_BY_ID = gql`query($id:String!){
	quote(id:$id){
		id
		version
		employeeEmail
		quoteState
		quoteNumber
		percentageDiscount
		totalPrice{
			centAmount,
			currencyCode
		}
		company{
			id,
			name
		}
		lineItems{
			quantity
			price{
				value{
				currencyCode
				centAmount
				}
			}
			originalPrice{
				centAmount
				currencyCode
			}
			totalPrice{
				centAmount
				currencyCode
			}
			nameAllLocales{
				locale
				value
			}
			variant{
				sku
				price{
				value{
					centAmount
					currencyCode
					}
				}
			}
		}
	}
}
`